import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Social App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={montserrat.className}>
        <body>
          <div className="w-full  px-4  md:px-8 lg:px-12 xl:px-24 2xl:px-48">
            <Navbar />
          </div>
          <div className="bg-slate-100 px-4  md:px-8 lg:px-12 xl:px-24 2xl:px-48 h-[calc(100vh-80px)]">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
